name: Serverless Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: "What is the environment for this deployment?"
        required: true
        type: string
      region:
        description: "What AWS Region should be used for this deployment?"
        required: false
        type: string
      release_tag:
        description: "What Release should be deployed? (enter the name of the tag)"
        required: true
        type: string
      artifact_name:
        description: "What should the name of the created artifact be?"
        required: true
        type: string

    # secrets:
    #   token:
    #     # required: true

concurrency: 
  group: "${{ inputs.environment }}-serverless-deploy-artifact"
  cancel-in-progress: false

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs: 
  deploy:
    #needs: [check-if-release, test, package]
    runs-on: ubuntu-20.04
    steps:
      # - name: Block Deployment To Prod If Invalid
      #   if: ${{inputs.environment == 'prod' && needs.check-if-release.outputs.prod_ready == 'false'}}
      #   run: |
      #     exit 0
      # - name: Block Deployment to Prod if Tests Failing
      #   if: ${{ inputs.environment == 'prod' && needs.test.result != 'success' }}
      #   run: |
      #     exit 1
      - name: Download Deployment Package
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
      - name: Unzip Deployment Package
        run: |
          unzip $package_name
        env:
          package_name: ${{ inputs.artifact_name }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
      - name: Install Serverless
        run: |
          npm install -g serverless
      - name: Configure PROD AWS Credentials
        if: ${{ inputs.environment == 'prod' || inputs.environment == 'stage' }}
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::948264521192:role/github-oidc-provider-Role-18M41E6WZ2630
          aws-region: ${{ inputs.region }}
      - name: Configure DEV/TEST AWS Credentials
        if: ${{ inputs.environment == 'dev' || inputs.environment == 'test' }}
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::284581930156:role/Github-Actions-OIDC-Role-1SFGCE3V2MLNB
          aws-region: ${{ inputs.region }}
      - name: Deploy Serverless Package to ${{ inputs.environment }}
        run: |
          serverless deploy --package .serverless --stage ${{ inputs.environment }} --region ${{ inputs.region }}

  