name: Update Workflow

on:
  workflow_call:
    inputs:
      workflow:
        description: "What Workflow to Update?"
        required: true
        type: string
    secrets: 
      GH_CICD_BOT_TOKEN:
        required: true


concurrency: 
  group: workflow-updates
  cancel-in-progress: false

jobs:
  update-wf:
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with: 
          token: ${{ secrets.GH_CICD_BOT_TOKEN }}
      - name: Checkout Github Actions repo
        uses: actions/checkout@v3
        with:
          repository: Genomic-Life/github-actions
          path: github-actions     
      - name: build-release-list
        id: build-release-list
        uses: actions/github-script@v6
        with:
          script: |
            const workflowHelper = require('./github-actions/scripts/workflowHelper.js')
            releaseList = workflowHelper.buildReleaseList(github, context, include_unapproved = true)
            console.log(releaseList);
            return releaseList

      - name: update-deploy-wf
        id: update-deploy-wf
        run: |
          output=${{ steps.build-release-list.outputs.result }}
          sed "s/\$RELEASE_OPTIONS/$output/g" $GITHUB_WORKSPACE/.github/templates/$WORKFLOW.template.yml > $GITHUB_WORKSPACE/.github/workflows/$WORKFLOW.yml
        env:
          WORKFLOW: ${{ inputs.workflow }}
      - name: git-stuff
        id: git-stuff
        run: |
          git config --global user.email "GH-CICD-BOT"
          git config --global user.name "GH-CICD-BOT"
          git add .github/workflows
          git commit -m "Generated Release List"
          git push
