name: Run Pytest Tests

on:
  workflow_call:
    inputs:
      python_version:
        description: "What is the python version for this project?"
        required: true
        type: string

concurrency: 
  group: "${{ inputs.environment }}-pytest"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: Pip install everything
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CICD_BOT_TOKEN }}
        run: |
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest